spring.datasource.url=jdbc:postgresql://localhost:5432/fustaniabc_db
spring.datasource.username=postgres
spring.datasource.password=Ahijeker12345
spring.jpa.hibernate.ddl-auto=update
jwt.secret=hQ7mF8R9L2p3MntV4qEs1dYAWz9fJXoNbZcD+Jea1Rw=

